### ISSUE TITLE
Redis Feature Requester doesn't allow to set up connection timeout

### ISSUE THREAD

**Issue by jjozefowicz** [launchdarkly/php-client#112]
Redis Feature Requester doesn't allow to set up connection timeout - therefore on any connectivity problems it waits unnecesarily 5 seconds.
Predis itself supports 'timeout' flag, float value - https://github.com/nrk/predis/wiki/Connection-Parameters

**Comment by eli-darkly** [comment]
This is in the 3.5.0 release.
