### ISSUE TITLE
2.0.0 requires psr/log 1.0.0 explicitly

### ISSUE THREAD

**Issue by bradynpoulsen** [launchdarkly/php-client#60]
`master` is versioned to psr/log version `1.0.*` however v2 (including 2.0.0 and 2.0.1) is versioned explicitly to psr/log version `1.0.0`

**Comment by drichelson** [comment]
@bradynpoulsen we're no longer using the v2 branch. For development we are branching from master, then releasing from master. Sorry for the confusion. I'm closing this issue. If you still have questions, please email support@launchdarkly.com
